/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.code.server.rpc.idl;


import org.apache.thrift.TEnum;

public enum ChargeType implements TEnum {
  money(1),
  gold(2);

  private final int value;

  private ChargeType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ChargeType findByValue(int value) { 
    switch (value) {
      case 1:
        return money;
      case 2:
        return gold;
      default:
        return null;
    }
  }
}
