package com.code.server.db.model;

import org.hibernate.annotations.DynamicUpdate;

import javax.persistence.*;
import java.util.Date;

/**
 * Created by win7 on 2017/3/8.
 */
@DynamicUpdate
@Entity
@Table(name = "users",
        indexes = {@Index(name = "userId", columnList = "userId"),
                    @Index(name="openId",columnList = "openId")})
public class User {
    // ==============
    // PRIVATE FIELDS
    // ==============
    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;


    @Column(nullable = false,unique=true)
    private long userId;

    @Column(nullable = false)
    private String account;

    @Column(nullable = false)
    private String password;

    @Column(columnDefinition = "varchar(4000)")
    private String username;

    @Column(nullable = false)
    private String ipConfig;

    @Column(columnDefinition = "double(18,2) default 0")
    private double money;//虚拟货币

    @Column(columnDefinition = "double(18,2) default 0")
    private double cash;//货币

    @Column(columnDefinition = "varchar(4000)")
    private String image;//头像

    @Column(columnDefinition = "double(18,2) default 0")
    private double rebate;//返利

    @Column(columnDefinition = "int default 0")
    private int referee;

    private int vip;//vip

    private String fatherId;//代理id

    private String uuid;//uuid

    private String openId;//openId

    private int sex;//

    private String aliId;

    @Column(columnDefinition = "varchar(2000)")
    private String email;

    private Date registDate;

    private Date lastLoginDate;

    private String column1;

    private String column2;

    private String column3;

    private String column4;

    @Column(columnDefinition = "text")
    private String column5;//text类型

    @Lob
    @Column(columnDefinition = "LONGTEXT")
    private String recordStr;

    @Transient
    private Record record;

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public long getUserId() {
        return userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    public String getUsername() {
        return username;
    }

    public User setUsername(String username) {
        this.username = username;
        return this;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getIpConfig() {
        return ipConfig;
    }

    public void setIpConfig(String ipConfig) {
        this.ipConfig = ipConfig;
    }

    public double getMoney() {
        return money;
    }

    public void setMoney(double money) {
        this.money = money;
    }

    public double getCash() {
        return cash;
    }

    public void setCash(double cash) {
        this.cash = cash;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }



    public String getFatherId() {
        return fatherId;
    }

    public void setFatherId(String fatherId) {
        this.fatherId = fatherId;
    }

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public String getOpenId() {
        return openId;
    }

    public void setOpenId(String openId) {
        this.openId = openId;
    }

    public int getVip() {
        return vip;
    }

    public User setVip(int vip) {
        this.vip = vip;
        return this;
    }

    public int getSex() {
        return sex;
    }

    public User setSex(int sex) {
        this.sex = sex;
        return this;
    }

    public String getAliId() {
        return aliId;
    }

    public void setAliId(String aliId) {
        this.aliId = aliId;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Date getRegistDate() {
        return registDate;
    }

    public void setRegistDate(Date registDate) {
        this.registDate = registDate;
    }

    public Date getLastLoginDate() {
        return lastLoginDate;
    }

    public void setLastLoginDate(Date lastLoginDate) {
        this.lastLoginDate = lastLoginDate;
    }

    public String getColumn1() {
        return column1;
    }

    public void setColumn1(String column1) {
        this.column1 = column1;
    }

    public String getColumn2() {
        return column2;
    }

    public void setColumn2(String column2) {
        this.column2 = column2;
    }

    public String getColumn3() {
        return column3;
    }

    public void setColumn3(String column3) {
        this.column3 = column3;
    }

    public String getColumn4() {
        return column4;
    }

    public void setColumn4(String column4) {
        this.column4 = column4;
    }

    public String getColumn5() {
        return column5;
    }

    public void setColumn5(String column5) {
        this.column5 = column5;
    }

    public String getRecordStr() {
        return recordStr;
    }

    public User setRecordStr(String recordStr) {
        this.recordStr = recordStr;
        return this;
    }

    public Record getRecord() {
        return record;
    }

    public User setRecord(Record record) {
        this.record = record;
        return this;
    }

    public double getRebate() {
        return rebate;
    }

    public User setRebate(double rebate) {
        this.rebate = rebate;
        return this;
    }
} // class User